### ISSUE TITLE
Hello there

### ISSUE THREAD

**Issue by fcvalise** [FriendSea/ProceduralGrass#1]
Hello FriendSea, I'm contacting you because I started using your grass shader for a game prototype. And I'm really enjoying playing with it. First of all, thank you for the job done. Otsukare Sama ! (is that a proper way to use it ? :)

I don't have clear plans in mind for that game yet. But I was wondering if you'll be okay if I use it in a commercial project ? And maybe if I dream, have some help from you, if time is something you have :)

Have a great day !

**Comment by FriendSea** [comment]
Otsukaresama-desu. (this word is frequentry used as greeting like this, more than original meaning)

You can use the grass shader in commercial project.
(The repositry is open to public as "MIT Licence")

I'm not sure if I can help you because I may have no time.
But it is welcome to giving some requests or ideas.
